npm:
  extends:
    file: docker-compose-demo.yml
    service: npm

sass:
  extends:
    file: docker-compose-demo.yml
    service: sass

web:
  extends:
    file: docker-compose-demo.yml
    service: web
  ports:
   - "8001:5000"

sass-watch:
  extends:
    file: docker-compose-demo.yml
    service: sass-watch
