base:
  image: ubuntu:14.04
  working_dir: /srv
  volumes:
    - .:/srv

assets:
  extends: {'service': 'base', 'file': 'docker-compose.yml'}
  links:
    - web
  build: .
  dockerfile: Dockerfile-assets
  command: /bin/bash -c 'umask 0000 && npm install && gulp dev'

web:
  extends: {'service': 'base', 'file': 'docker-compose.yml'}
  build: .
  ports:
    - "8001:5000"
