base:
  image: ubuntu:14.04
  working_dir: /srv
  volumes:
    - .:/srv

npm:
  extends: {'service': 'base', 'file': 'docker-compose.yml'}
  build: .
  dockerfile: Dockerfile-npm
  command: /bin/bash -c 'umask 0000 && npm install && gulp watch'

web:
  extends: {'service': 'base', 'file': 'docker-compose.yml'}
  build: .
  ports:
    - "8001:5000"
