backend:
  name: github
  repo: nottrobin/www.ubuntu.com
  branch: netlify-legal
  site_domain: frosty-ritchie-5e240a.netlify.com

media_folder: 'static'

collections:
  - name: "legal" # Used in routes, e.g. /admin/collections/blog
    label: "Legal" # Used in the UI
    files:
      - name: "websites"
        label: "Websites"
        delete: false
        file: "templates/legal/websites.md"
        fields: # The fields for each document, usually in front matter
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - name: "intellectual-property-policy"
        label: "Intellectual property policy"
        delete: false
        file: "templates/legal/terms-and-policies/intellectual-property-policy/index.md"
        fields: # The fields for each document, usually in front matter
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Sidebar templates", name: "sidebar-templates", widget: "list"}
          - {label: "Body", name: "body", widget: "markdown"}

publish_mode: editorial_workflow
